### ISSUE TITLE
Doesn't handle <footer>

### ISSUE THREAD

**Issue by stig** [programble/writ#1]
Perhaps add a default style for &lt;footer>? On my blog I put the nav at the bottom of the article in a &lt;footer>  tag, to leave the top clutter-free. Tried to convert it to use this CSS and although most of the site worked well the footers did not.

**Comment by causal-agent** [comment]
The only style I can think of for a footer is to just centre the text like the header. Would that be enough?

**Comment by stig** [comment]
> On 24 Aug 2015, at 23:50, Curtis McEnroe notifications@github.com wrote:
> 
> The only style I can think of for a footer is to just centre the text like the header. Would that be enough?
> 
> I think so, as the header looked OK on my blog :-)

Stig

**Comment by citizenk** [comment]
Centered or perhaps left-aligned, but with a slightly smaller text would that work for you, stig? I'm specifically thinking of the traditional academic-style footers, with info on last update date, license, and so on, [like here for instance](http://cui.unige.ch/isi/icle-wiki/publications)

Anyway, I agree that footers would nicely complete writ.css

**Comment by stig** [comment]
I went with slightly lighter text, left justified: http://www.superloopy.io/articles/2015/benchmarking.html -- Here's my amendments to writ's CSS: http://www.superloopy.io/css/main.css

**Comment by citizenk** [comment]
Love it, stig: exactly what I tried to describe!

Don't know if this is of interest for programble, but I also saw [this suggestion](https://news.ycombinator.com/item?id=10115252) over on HN. Just FYI.

**Comment by carc1n0gen** [comment]
@stig Did you know that grey text on white is basically impossible for coloured blind people to see?

**Comment by stig** [comment]
Hm. It didn't occur to me, no. Are you referring to the light heat in the footer, or also to the dark grey of the main body text?

**Comment by carc1n0gen** [comment]
@stig Was talking about the footer text

**Comment by stig** [comment]
Thanks for confirming. I'll try to improve on it.
