### ISSUE TITLE
rem instead of em

### ISSUE THREAD

**Issue by jonathanhefner** [programble/writ#12]
Any thoughts on using `rem` instead of `em` for units?  They appear to be [fully supported](http://caniuse.com/#feat=rem) on the browsers you are targeting (and then some).

**Comment by causal-agent** [comment]
Where would it be advantageous to use `rem` over `em`?

**Comment by jonathanhefner** [comment]
This [article](http://snook.ca/archives/html_and_css/font-size-with-rem) does a good job of explaining where you can go wrong with `em`, I think.  Basically, `em` is cumulative.  So if you have two elements that set text size to 1.2em, and then you nest one inside the other, the nested element will suddenly have a text size of 1.44em, which probably isn't what you intended.

**Comment by causal-agent** [comment]
Now using `rem` where it makes sense.
