### ISSUE TITLE
Vertical rhythm

### ISSUE THREAD

**Issue by jonathanhefner** [programble/writ#14]
Since you have opinionated sizes for headline and body text, you can establish a strong [vertical rhythm](http://webdesign.tutsplus.com/articles/improving-layout-with-vertical-rhythm--webdesign-14070).  This [calculator](https://drewish.com/tools/vertical-rhythm/) is handy for visualizing and verifying sizes.  The calculator unfortunately requires target sizes input as pixels, but as you can see the resulting CSS uses relative units (`em`).

**Comment by causal-agent** [comment]
Thanks for the tip. Most of this was admittedly guesswork and refreshing a page a bunch.

**Comment by citizenk** [comment]
A good reference (and upcoming book) that may help you with typographical best practices is http://webtypography.net/toc

HTH
