### ISSUE TITLE
Use rgba for gray backgrounds

### ISSUE THREAD

**Issue by jonathanhefner** [programble/writ#15]
Using `rgba(0, 0, 0, 0.05)` instead of `#eee` for gray backgrounds enables people to override the body background color (e.g. to a light gray or light blue) while preserving slightly darker `<pre>`, `<code>`, etc.  Also, in my opinion, `#eee` is a shade too dark.  Using `rgba(0, 0, 0, 0.05)` (equivalent to `#f2f2f2` on a white background) provides better contrast.

Related: should the background colors for the above elements be grouped together in a single rule like [this one](https://github.com/programble/writ/blob/692dd8b4bc967216d924688c11aa19b0ccf475ba/writ.css#L33)?

**Comment by causal-agent** [comment]
Good point. (The reason it's `#eee` is because I have a thing for three-digit hex colours...)

**Comment by jonathanhefner** [comment]
>  The reason it's #eee is because I have a thing for three-digit hex colours...

Haha, I'm the same way.  I think it's some combination of OCD and formerly always having to use [web-safe colors](https://en.wikipedia.org/wiki/Web_colors#Web-safe_colors).  I feel like `rgba` alleviates the OCD to some extent though. ;)
